apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wayfarer-posts-ingress
  namespace: wayfarer
spec:
  ingressClassName: "gce" 
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wayfarer-posts-service
            port:
              number: 80
