apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wayfarer-posts-ingress
  namespace: wayfarer
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: wayfarer-posts.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wayfarer-posts-service
            port:
              number: 80
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wayfarer-posts-service
            port:
              number: 80
