apiVersion: v1
kind: Service
metadata:
  name: wayfarer-posts-service
  namespace: default
  labels:
    app: wayfarer-posts-service
spec:
  type: ClusterIP
  selector:
    app: wayfarer-posts-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8081
