apiVersion: v1
kind: ConfigMap
metadata:
  name: wayfarer-posts-config
  namespace: wayfarer
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: wayfarerDB
  DB_USER: postgres
  ASPNETCORE_ENVIRONMENT: Production
